// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Proj_OrionBeacon.Dados;

#nullable disable

namespace Proj_OrionBeacon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proj_OrionBeacon.Models.Analise", b =>
                {
                    b.Property<int>("IdAnalise")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANALISE");

                    b.Property<string>("ClassificacaoFinal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CLASSIFICACAO_FINAL");

                    b.Property<DateTime>("DataAnalise")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ANALISE");

                    b.Property<int>("IdArea")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AREA");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("OBSERVACOES");

                    b.HasKey("IdAnalise");

                    b.HasIndex("IdArea");

                    b.ToTable("TB_ANALISE");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.AreaAnalisada", b =>
                {
                    b.Property<int>("IdArea")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AREA");

                    b.Property<int>("IdCorpo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CORPO");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("NUMBER(10,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("NUMBER(10,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("NomeArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_AREA");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REGIAO");

                    b.Property<decimal>("ScoreRanking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("SCORE_RANKING");

                    b.Property<string>("TipoTerreno")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_TERRENO");

                    b.HasKey("IdArea");

                    b.HasIndex("IdCorpo");

                    b.ToTable("TB_AREA_ANALISADA");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.CorpoCeleste", b =>
                {
                    b.Property<int>("IdCorpo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CORPO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME");

                    b.HasKey("IdCorpo");

                    b.ToTable("TB_CORPO_CELESTE");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.LeituraSensor", b =>
                {
                    b.Property<int>("IdLeitura")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA");

                    b.Property<int>("IdAnalise")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANALISE");

                    b.Property<int>("IdSensor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<string>("Interpretacao")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("INTERPRETACAO");

                    b.Property<decimal>("ValorLido")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VALOR_LIDO");

                    b.HasKey("IdLeitura");

                    b.HasIndex("IdAnalise");

                    b.HasIndex("IdSensor");

                    b.ToTable("TB_LEITURA_SENSOR");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.LogAnalise", b =>
                {
                    b.Property<int>("IdLog")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG");

                    b.Property<DateTime?>("DataLog")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_LOG");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("MENSAGEM");

                    b.HasKey("IdLog");

                    b.ToTable("TB_LOG_ANALISE");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.Missao", b =>
                {
                    b.Property<int>("IdMissao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MISSAO");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_INICIO");

                    b.Property<int>("IdArea")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AREA");

                    b.Property<string>("NomeMissao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_MISSAO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.HasKey("IdMissao");

                    b.HasIndex("IdArea");

                    b.ToTable("TB_MISSAO");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.NosqlAreaJson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Documento")
                        .HasColumnType("CLOB")
                        .HasColumnName("DOCUMENTO");

                    b.HasKey("Id");

                    b.ToTable("TB_NOSQL_AREA_JSON");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.Sensor", b =>
                {
                    b.Property<int>("IdSensor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("NomeSensor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_SENSOR");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_SENSOR");

                    b.HasKey("IdSensor");

                    b.ToTable("TB_SENSOR");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.Analise", b =>
                {
                    b.HasOne("Proj_OrionBeacon.Models.AreaAnalisada", "Area")
                        .WithMany("Analises")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ANALISE_AREA");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.AreaAnalisada", b =>
                {
                    b.HasOne("Proj_OrionBeacon.Models.CorpoCeleste", "CorpoCeleste")
                        .WithMany("Areas")
                        .HasForeignKey("IdCorpo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AREA_CORPO");

                    b.Navigation("CorpoCeleste");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.LeituraSensor", b =>
                {
                    b.HasOne("Proj_OrionBeacon.Models.Analise", "Analise")
                        .WithMany("Leituras")
                        .HasForeignKey("IdAnalise")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_LEITURA_ANALISE");

                    b.HasOne("Proj_OrionBeacon.Models.Sensor", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("IdSensor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_LEITURA_SENSOR");

                    b.Navigation("Analise");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.Missao", b =>
                {
                    b.HasOne("Proj_OrionBeacon.Models.AreaAnalisada", "Area")
                        .WithMany("Missoes")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_MISSAO_AREA");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.Analise", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.AreaAnalisada", b =>
                {
                    b.Navigation("Analises");

                    b.Navigation("Missoes");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.CorpoCeleste", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Proj_OrionBeacon.Models.Sensor", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
